[pytest]
addopts = -v -s 
testpaths = Tests
markers =
    smoke: smoke tests
    integration: integration tests
    negative: negative tests
    security: security tests
    schema: schema validation tests